
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - notifier.email.informer.io
  resources:
  - failureinformers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - notifier.email.informer.io
  resources:
  - failureinformers/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pod
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pod/status
  verbs:
  - get
  - list
  - watch
