
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - email.notify.io
  resources:
  - notifiers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - email.notify.io
  resources:
  - notifiers/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - event
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secret
  verbs:
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - secret/status
  verbs:
  - get
  - watch
